# -*- coding: utf-8 -*-
"""One_hot_encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nXNvAb5edfj-fNFTc42sUDdNEpuxpJfu
"""

import numpy as np
from sklearn.preprocessing import OneHotEncoder
colors = ['Red', 'Green','Orange', 'Blue']
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')
colors_2d = np.array(colors).reshape(-1, 1)
one_hot_encoded = encoder.fit_transform(colors_2d)
one_hot_encoded

import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
data={'category':['A','B','C','D']}
df=pd.DataFrame(data)
encoder=OneHotEncoder(sparse=False)
encoded_data=encoder.fit_transform(df[['category']])
df

df_encoded=pd.DataFrame(encoded_data,columns=encoder.get_feature_names_out(['category']))
df_encoded

df=pd.concat([df,df_encoded],axis=1)
df